---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  enabled: False

platforms:
  - name: instance1
    image: centos:6
    publish_all_ports: true
    port_bindings:
      - 17001:7001
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: True

  - name: instance2
    # Failed to get D-Bus connection: Operation not permitted
    image: centos/systemd
    publish_all_ports: true
    port_bindings:
      - 7001:7001
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    # Failed to get D-Bus connection: Operation not permitted
    privileged: True
    # Failed to get D-Bus connection: Operation not permitted
    command: /sbin/init

provisioner:
  name: ansible
  options:
    vvv: false
  lint:
    name: ansible-lint

scenario:
  name: default

verifier:
  name: testinfra
  lint:
    name: flake8
