---
- name: Flatten vars
  template:
    src: vars/main.yml
    dest: /Users/koydooley/PycharmProjects/molecule/weblogic/molecule/default/tests/flat.yml
  delegate_to: localhost

- name: Add group
  group:
    name: oinstall
    gid: 500

- name: Add user
  user:
    name: oracle
    comment: Oracle
    uid: 1000
    group: oinstall

- name: Create installation dir
  file:
    path: "{{ item }}"
    state: directory
    owner: oracle
    group: oinstall
  with_items: "{{ common.install_dirs }}"

- name: Install netstat
  yum:
    name: net-tools
    state: latest
