---
- name: Check if domain is installed
  stat:
    path: "{{ domain.path }}/{{ domain.name }}"
  register: domain_check
  tags:
    - domain
    -
- name: Message
  debug:
    msg: "Creating Domain: {{ domain.name }}"
  when: domain_check.stat.exists == False
  tags:
    - domain
    -
- name: Stage create_domain.wlst
  template:
    src: "{{ domain.template_dir }}/create_domain.wlst.j2"
    dest: "{{ stage_dir }}/create_{{ domain.name }}.wlst"
  tags:
    - domain

- name: Create Domain
  command: "{{ weblogic.mw_home }}/oracle_common/common/bin/wlst.sh {{ stage_dir }}/create_{{ domain.name }}.wlst"
  become: true
  become_user: "{{ os_user }}"
  register: create_domain_out
  changed_when: " 'Domain Created' in create_domain_out.stdout "
  when: domain_check.stat.exists == False
  tags:
    - domain

- name: Create security dir
  file:
    path: "{{ domain.path }}/{{ domain.name }}/servers/{{ domain.adminserver }}/security"
    state: directory
  become: true
  become_user: "{{ os_user }}"
  tags:
    - domain

- name: Create boot.properties
  template:
    src: "{{ domain.template_dir }}/boot.properties.j2"
    dest: "{{ domain.path }}/{{ domain.name }}/servers/{{ domain.adminserver }}/security/boot.properties"
  become: true
  become_user: "{{ os_user }}"
  tags:
    - domain
