---
- include: "distribution/{{ ansible_distribution }}/{{ ansible_distribution_major_version }}/prereq.yml"

- include: common.yml

- include: java.yml

- include: weblogic.yml

- include: domain.yml

- include: "distribution/{{ ansible_distribution }}/{{ ansible_distribution_major_version }}/nodemanager.yml"

- include: managedserver.yml
