---
# ----------------------------------------------------------------------------------------------------------------------
# Main ansible file used to call other files.
# Each included file should contain all the tasks necessary to complete that part of the installation.
# ----------------------------------------------------------------------------------------------------------------------
- include: "distribution/{{ ansible_distribution }}/{{ ansible_distribution_major_version }}/prereq.yml"
  tags:
    - java
    - weblogic
    - domain
    - nodemanager
    - managedserver

- include: common.yml
  tags:
    - java
    - weblogic
    - domain
    - nodemanager
    - managedserver

- include: java.yml
  tags:
    - java

- include: weblogic.yml
  tags:
    - weblogic

- include: domain.yml domain="{{ item }}"
  with_items: "{{ domains }}"
  tags:
    - domain

- include: managedserver.yml domain="{{ domain_items }}"
  with_items: "{{ domains }}"
  loop_control:
    loop_var: domain_items
  tags:
    - domain
    - managedserver

- include: "distribution/{{ ansible_distribution }}/{{ ansible_distribution_major_version }}/nodemanager.yml domain={{ domain_items }}"
  with_items: "{{ domains }}"
  loop_control:
    loop_var: domain_items
  tags:
    - domain
    - nodemanager

- include: start_nm.yml domain="{{ domain_items }}"
  with_items: "{{ domains }}"
  loop_control:
    loop_var: domain_items
  tags:
    - start

- include: start_admin.yml domain="{{ domain_items }}"
  with_items: "{{ domains }}"
  loop_control:
    loop_var: domain_items
  tags:
    - start

- include: stop_admin.yml domain="{{ domain_items }}"
  with_items: "{{ domains }}"
  loop_control:
    loop_var: domain_items
  tags:
    - stop
