- name: nodemanager.yml - Create installation dir
  file:
    path: "{{ item }}"
    state: directory
    owner: oracle
    group: oinstall
  with_items:
    - "{{ nodemanager.lifecycle_dir }}"

- name: Stage lifecycle scripts
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: oracle
    group: oinstall
  with_items:
    - { 'src': "templates/init/nodemanager.service.j2", 'dest' : "/usr/lib/systemd/system/nodemanager.service" }
    - { 'src': "templates/lifecycle/nodemanager/nodemanager.domains.j2", 'dest' : "{{ nodemanager.home }}/nodemanager.domains" }
    - { 'src': "templates/lifecycle/nodemanager/nodemanager.properties.j2", 'dest' : "{{ nodemanager.home }}/nodemanager.properties" }

- name: Make sure a service is running
  systemd:
    state: started
    name: nodemanager
    daemon_reload: yes
    enabled: yes
