- name: Message
  debug:
    msg: "Creating Node Manager for server '{{ managedserver.name }}' in domain '{{ domain.name }}'"
  tags:
    - domain
    - managedserver
    - nodemanager

- name: Stage nodemanager scripts
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: oracle
    group: oinstall
  with_items:
    - { 'src': "templates/nodemanager/nodemanager.service.j2", 'dest' : "/usr/lib/systemd/system/nodemanager.service" }
    - { 'src': "templates/nodemanager/nodemanager.domains.j2", 'dest' : "{{ domain.path }}/{{ domain.name }}/nodemanager/nodemanager.domains" }
    - { 'src': "templates/nodemanager/nodemanager.properties.j2", 'dest' : "{{ domain.path }}/{{ domain.name }}/nodemanager/nodemanager.properties" }
  when: ansible_distribution_major_version == '7'
  tags:
    - domain
    - managedserver
    - nodemanager

- name: Start nodemanager
  systemd:
    state: started
    name: nodemanager
    daemon_reload: yes
    enabled: yes
  when: ansible_distribution_major_version == '7'
  tags:
    - domain
    - managedserver
    - nodemanager
