- name: Message
  debug:
    msg: "Creating Node Manager for server '{{ managedserver.name }}' in domain '{{ domain.name }}'"
  tags:
    - domain
    - managedserver
    - nodemanager

- name: Create required dirs
  file:
    path: "{{ nodemanager_dir_item }}"
    state: directory
  with_items:
    - "{{ managedserver.nodemanager.lifecycle_dir }}"
  loop_control:
    loop_var: nodemanager_dir_item

- name: Stage lifecycle scripts
  template:
    src: "{{ nodemanager_scipt_item.src }}"
    dest: "{{ nodemanager_scipt_item.dest }}"
    owner: oracle
    group: oinstall
  with_items:
    - { 'src': "templates/nodemanager/nodemanager.j2", 'dest' : "/etc/init.d/nodemanager_{{ domain.name }}" }
    - { 'src': "templates/nodemanager/nodemanager.domains.j2", 'dest' : "{{ managedserver.nodemanager.home }}/nodemanager.domains" }
    - { 'src': "templates/nodemanager/nodemanager.properties.j2", 'dest' : "{{ managedserver.nodemanager.home }}/nodemanager.properties" }
    - { 'src': "templates/nodemanager/stop.wlst.j2", 'dest' : "{{ managedserver.nodemanager.lifecycle_dir }}/stop.wlst" }
    - { 'src': "templates/nodemanager/nm_password.properties.j2", 'dest' : "{{ domain.home }}/config/nodemanager/nm_password.properties" }
  loop_control:
    loop_var: nodemanager_scipt_item
  when: ansible_distribution_major_version == '6'

- name: Change permission for /etc/init.d/nodemanager
  file:
    path: /etc/init.d/nodemanager
    mode: 0755

- name: Start nodemanager
  service:
    name: nodemanager
    state: started
    enabled: true
  when: ansible_distribution_major_version == '6'
